image: ekino/docker-buildbox:nightly-node12

pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  before_script:
    - npm install
  script:
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  only:
    - main
